# You can use this file to create a conda environment for this pipeline:
#   conda env update -f environment.yml -n base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8
  - emboss=6.6.0
  - bowtie2=2.3.4.3
  - bwa=0.7.17
  - trim-galore=0.5.0
  - kraken=1.1
  - krona=2.7.1
  - samtools=1.9
  - bedtools=2.27.1
  - picard=2.19.0
  - gatk=3.8
  - spades=3.13.0
  - quast=5.0.2
  - multiqc=1.6
  - qualimap=2.2.2a
  - preseq=2.0.3
  - perl-bioperl=1.7.2
  - minced=0.3.0
  - prokka=1.12
  - diamond=0.9.24
  - biopython=1.73
  - cgecore=1.5.1
  - anaconda::tabulate=0.8.3
  - bioconda::nextflow=19.01.0
  - graphviz
  - ruby=2.6.5
  - r-base=3.5.1
  - r::r-essentials=3.5.1
  - r::r-rcurl=1.95_4.11
  - bioconductor-rhtslib=1.14.0
  - bioconductor-biobase=2.42.0
  - bioconductor-biocgenerics=0.28.0
  - bioconductor-s4vectors=0.20.1
  - bioconductor-iranges=2.16.0
  - bioconductor-zlibbioc=1.28.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-xvector=0.22.0
  - bioconductor-biocparallel=1.16.2
  - bioconductor-genomeinfodb=1.18.1
  - bioconductor-biostrings=2.50.2
  - bioconductor-summarizedexperiment=1.12.0
  - bioconductor-rsamtools=1.34.0
  - bioconductor-genomicalignments=1.18.1
  - bioconductor-delayedarray=0.8.0
  - bioconductor-dnacopy=1.56.0
